#include <iostream>
#include <queue>
#include <set>
#include <sstream>
#include <algorithm>
#include <map>
#include <vector>

#define mp make_pair
#define pb push_back
#define sqr(x) ((x)*(x))
#define foreach(it,c) for(typeof((c).begin()) it = (c).begin(); it != (c).end(); ++it)

using namespace std;

typedef vector<int> VI;
typedef vector<VI> VVI;
typedef vector<string> VS;
typedef pair<int,int> PII;
typedef long long LL;

template<typename T> int size(const T &a) { return a.size(); }

int N, M;
vector<int> pow;
vector<string> bond;

struct state {
    state(int pos, LL dis, int pc) : pos(pos), dis(dis), pick_cnt(pc) {};

    int pos;
    LL dis;
    int pick_cnt;

    bool operator<(const state &rhs) const {
        if(pos != rhs.pos) return pos < rhs.pos;
        if(pick_cnt != rhs.pick_cnt) return pick_cnt < rhs.pick_cnt;
        return dis < rhs.dis;
    }
};

map<state, int> memo;

int go(int a, LL dis, int pc) {
    if(N-a + pc < M) return -1;
    if(a == N) {
        return 0;
    }
    if(dis & 1) {
        return go(a+1, dis >> 1, pc);
    }

    state key(a, dis, pc);
    if(memo.count(key)) return memo[key];

    int tmp1 = go(a+1, dis >> 1, pc);
    dis >>= 1;
    for(int i=a+1;i<N;i++) if(bond[a][i] == 'N') {
        int pp = i - a - 1;
        dis |= (1LL << pp);
    }
    int tmp2 = go(a+1, dis, pc + 1);
    if(tmp2 != -1) tmp2 += pow[a];

    return memo[key] = max(tmp1, tmp2);
}

class MagicMolecule 
{
public:
    int maxMagicPower(vector <int> magicPower, vector <string> magicBond) 
    {		
        pow = magicPower;
        bond = magicBond;
        memo.clear();
        N = size(pow);
        M = (N * 2 + 2) / 3;

        /*
        cout << M << endl;
        for(int i=0;i<N;i++) {
            cout << i << " : ";
            for(int j=0;j<N;j++) if(i != j) {
                if(bond[i][j] == 'N') {
                    cout << j << " ";
                }
            }
            cout << endl;
        }
        */

        return go(0, 0, 0);
    }

    

};


int main(void) {

    int data[50] = { 69383,40886,52777,56915,77793,78335,75386,70492,96649,31421,22362,50027,18690,30059,17763,33926,70540,43426,79172,85736,95211,55368,52567,46429,55782,91530,92862,35123,34067,83135,13929,99802,24022,63058,63069,98167,41393,38456,75011,38042,66229,87373,84421,74919,23784,98537,15198,84324,48315,84370};
    string bond[50] = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY","YNYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YNYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN","YYYYYNYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYYYYYYY","YYYYYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYNYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY","YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY","YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYNYYYYYYYYYY","YYYYYYYNYYYYYNYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYNYYYY","YYYYYNYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYNYYYYNYYYYYYYNYNYYYYYYYNYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYNYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYNYNYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYNYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYNYYY","YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYNYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYYYYYYYYYYYNYYYYYYNYYYNYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY","YYYYYNYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYNYYYYYYYYYYYYY","YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYNYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYNYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY","NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYNYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYNYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYNYYYYYYYYYYYYYYNYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY","YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };

    vector<int> p(data, data+50);
    vector<string> b(bond, bond+50);

    MagicMolecule tt;
    cout << tt.maxMagicPower(p, b) << endl;
}

// Powered by FileEdit
// Powered by TZTester 1.01 [25-Feb-2003]
// Powered by CodeProcessor
