#include <iostream>
#include <queue>
#include <set>
#include <sstream>
#include <algorithm>
#include <map>
#include <vector>

#define mp make_pair
#define pb push_back
#define sqr(x) ((x)*(x))
#define foreach(it,c) for(typeof((c).begin()) it = (c).begin(); it != (c).end(); ++it)

using namespace std;

typedef vector<int> VI;
typedef vector<VI> VVI;
typedef vector<string> VS;
typedef pair<int,int> PII;
typedef long long LL;

template<typename T> int size(const T &a) { return a.size(); }

const int maxn = 52;

int N;
int A[maxn][maxn];
long long adj[maxn];
int cost[maxn];
int answer;
int p[maxn];
int was[maxn];

void bct(int ind, int cnt, LL mask) {
    if(ind == N) {
        if(3 * cnt < 2 * N) return;
        int cur = 0;
        for(int i=0;i<N;i++) {
            if(was[i]) cur += cost[i];
        }
        answer = max(answer, cur);
        return;
    }
    int cur = 0;
    int q = cnt;
    for(int i=0; i<ind; i++) 
        if(was[p[i]]) cur += cost[p[i]];
    for(int i=ind;i<N;i++) {
        if((1LL << p[i]) & mask) {
            cur += cost[p[i]];
            q++;
        }
    }
    if(3 * q < 2 * N) return;
    if(cur < answer) return;
    if(mask & (1LL << p[ind])) {
        was[p[ind]] = 1;
        bct(ind+1, cnt+1, mask & adj[p[ind]]);
    }
    was[p[ind]] = 0;
    bct(ind+1, cnt, mask);
}

class MagicMolecule 
{
public:
    int maxMagicPower(vector <int> magicPower, vector <string> magicBond) 
    {		
        N = size(magicPower);
        for(int i=0;i<N;i++) {
            p[i] = i;
            cost[i] = magicPower[i];
            for(int j=0;j<N;j++) {
                if(i == j) A[i][j] = 1;
                else A[i][j] = (magicBond[i][j] == 'Y');
                adj[i] |= (A[i][j] * 1LL) << j;
            }
        }

        srand(time(NULL));
        random_shuffle(p, p + N);
        answer = -1;
        bct(0, 0, (1LL << N) - 1);
        return answer;
    }
};

int main(void) {

    int data[50] = { 69383,40886,52777,56915,77793,78335,75386,70492,96649,31421,22362,50027,18690,30059,17763,33926,70540,43426,79172,85736,95211,55368,52567,46429,55782,91530,92862,35123,34067,83135,13929,99802,24022,63058,63069,98167,41393,38456,75011,38042,66229,87373,84421,74919,23784,98537,15198,84324,48315,84370};
    string bond[50] = { "NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY","YNYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YNYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN","YYYYYNYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYYYYYYY","YYYYYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYNYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY","YYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYY","YYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYNYYYYYYYYYY","YYYYYYYNYYYYYNYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYNYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYNYYYY","YYYYYNYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYNYYYYNYYYYYYYNYNYYYYYYYNYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYNYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYNYNYYYYYYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYNYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYNYYY","YYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYNYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYY","YYYYYYYYYYYYYYNYYYYYYYYYYYYNYYYYYYNYYYNYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYY","YYYYYNYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYNYYYYYYYYYYYYY","YYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYNYYYYYYYYYYY","YYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYNYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYYYYNYYYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYY","NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYYNYYYYY","YYYYYYYYYYYYYYYYYYYYYYYYNYYYYYYYNYYYYYYYYYYYYNYYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYNYYYYYYYYYYYYYYNYYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYY","YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNY","YYYYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYN" };

    vector<int> p(data, data+50);
    vector<string> b(bond, bond+50);

    MagicMolecule tt;
    cout << tt.maxMagicPower(p, b) << endl;
}




// Powered by FileEdit
// Powered by TZTester 1.01 [25-Feb-2003]
// Powered by CodeProcessor
